apiVersion: v1
kind: ConfigMap
metadata:
  name: transactions-api-config
  labels:
    app: transactions-api
data:
  NODE_ENV: 'production'
  PORT: '3000'
  DB_NAME: 'transactions_db'
  DB_PORT: '5432'
  FRAUD_TIME_WINDOW_MINUTES: '5'
  FRAUD_MAX_TRANSACTIONS: '3'
  FRAUD_AMOUNT_THRESHOLD: '1000'
